### ISSUE TITLE
Mutual Recursion: Maximum Depth 

### ISSUE THREAD

**Issue by ghost** [heywbj/django-rest-framework-recursive#20]
So I've followed your example use cases but I'm experiencing some issues. Here is the code I'm using:

```
class RequestSerial(ModelSerializer):

    bidpick = RecursiveField('BidSerial')


    class Meta:

        model = Request

        fields = '__all__'


class BidSerial(ModelSerializer):

    request = RequestSerial()


    class Meta:

        model = Bid

        fields = '__all__'
```

I definitely expected this to work but I'm getting a maximum recursion depth exceeded as a runtime error.

**Comment by heywbj** [comment]
That means you hit the end of the python call stack. Do you have a self referential object? If you have a cycle in the structure you are serializing that would cause this error

**Comment by ghost** [comment]
Yes, the `Request` model refers to the `Bid` model, which is initially null and blank. The `Bid` is attached to the `Request` on which the user is making their offer. Isn't the objective of this package to circumvent this issue?

**Comment by heywbj** [comment]
Let's say you have a Request 1, which refers to Bid 1, which refers to Request 1, which refers to Bid 1....

How do you expect this to serialize?

`
{
  request_id:1;
  bid: {
    bid_id:1,
    request: {
      request_id:1,
      bid: {
        bid_id:1,
    request: {
      request_id:1,
      bid: {
        bid_id:1,
    request: {
      request_id:1,
      bid: {
        bid_id:1,
    request: {
      request_id:1,
      bid: {
        bid_id:1,
    request: {
      request_id:1,
      bid: {
        bid_id:1,
....
`

It never ends. You see the problem? The package will allow you to try to serialize it, but you can still shoot yourself in the foot.
