### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by simjoh** [heywbj/django-rest-framework-recursive#27]
I tried to implement a recursive field. But I found the performance to be quite slow compared to two nested serializers. Is this expected. Note that I've tried the some different methods but with eqaul performance. The model has 20 items at top level each parent has 1-20 childs.

models.py
```
class City(models.Model):
  area = models.CharField(max_length=120)
  parent = models.ForeignKey('self', models.CASCADE, blank=True, null=True, related_name='subarea')

```

view.py
In order to reduce number of calls to databae I use the `prefetch_related()` method
```
class RegionsList(generics.ListCreateAPIView):
	serializer_class = RegionSerializer
	queryset = City.objects.filter(parent=None).prefetch_related('subarea') 

```
serializers.py
```
class CitySerializer(serializers.ModelSerializer):
    #This serializer is only used for the fast version with two levels in the output.
    class Meta:
        model = City
        fields = ('area','id')

class Region2Serializer(serializers.ModelSerializer):
    #Recursive but slow
    #subarea = RecursiveField2(many=True)
    #subarea = RecursiveField('City2Serializer', required=False,many=True)
    #subarea = RecursiveField(required=False, allow_null=True,many=True)
    subarea = serializers.ListSerializer(read_only=True, child=RecursiveField())
    #Fast but not recursive
    #subarea=City2Serializer(many=True)
    class Meta:
        model = City
        fields = ('area','id','subarea')
```
Analysing the calls with django toolbar the time goes from 0.1 to 4 seconds. And number of calls goes from 1 to the same number of calls as objects in the City model. 
Could I speed this up in any way? 
I want to have fully a recursive model but not at any cost.

**Comment by heywbj** [comment]
This isn't a problem with the serializer as much as how you are building the python object itself.

If you look at the tests, this field serializes a python object to a JSON object, but as for how you build the python object, that is beyond the scope of this project. You need to determine the best way to structure your database and database access so that each level of the recursion doesn't require another round-trip to the database.
