### ISSUE TITLE
Non-normal Primary Key name

### ISSUE THREAD

**Issue by ItsAcedia** [heywbj/django-rest-framework-recursive#28]
Thank you for your work on this plug-in. 

I hope this thread is still monitored. 

I am having an issue that I think is due to a non-defaulted primary key.  I am creating a Django stack for an existing MSSQL database, and have successfully integrated my database models with DRF.  However, due to the nature of the existing database, I am stuck using pre-determined field names, including primary key assignments.  

Model:

```
from django.db import models, connection

class ClientModel(models.Model):
    ClientID = models.IntegerField(primary_key=True)
    Name = models.CharField(max_length=100)
    BusinessUnitID = models.IntegerField(default=0)
    ParentID = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    InvoicePreFix = models.CharField(max_length=50, default="")
    BillingTerms = models.IntegerField(default=0)
    BillingInterval = models.IntegerField(default=0)
    MaximumAllowedExposure = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    InvoiceTypeID = models.IntegerField(default=0)

    @staticmethod
    def getClientList():
        cur = connection.cursor()
        cur.execute("{CALL getClientList}")
        results = cur.fetchall()
        cur.close()
        return [ClientModel(*row) for row in results]
```

Serializer:
```
class ClientModelSerializer(serializers.ModelSerializer):
    ParentID = RecursiveField(allow_null=True)

    class Meta:
        model = ClientModel
        fields = (
            'ClientID',
            'Name',
            'BusinessUnitID',
            'ParentID',
            'InvoicePreFix',
            'BillingTerms',
            'BillingInterval',
            'MaximumAllowedExposure',
            'InvoiceTypeID'
        )
```
After installation and implementation of DRF-Recursive, I am receiving the following error:

`('42S22', "[42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'Name'. (207) (SQLExecDirectW);_ [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'BusinessUnitID'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ParentID_id'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'InvoicePreFix'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'BillingTerms'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'BillingInterval'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'MaximumAllowedExposure'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'InvoiceTypeID'. (207); [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Statement(s) could not be prepared. (8180)")`

Of note, as shown in the error, my primary key field ("ClientID") is not included in the error report.  I could not find an example on the Git page that did not use Django's "id" default primary key field.

Also, my "ParentID" field is getting an "_id" appended to the end of the field name.  How can I allow this field name to remain the same?  
`
[Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ParentID_id'. (207); 
`

Thank you for your time and effort.

**Comment by ItsAcedia** [comment]
It might be worth mentioning that, because I am utilizing a pre-exisitng database instead of the provided Django SQLLite structure, I do not have the proper Django models implemented i.e migrations && foreign key implementation for other ID fields, such as "InvoiceTypeID"

**Comment by ItsAcedia** [comment]
I have updated my code to allow for proper implementation of the Django Models and migrations.  This helped prevent the previously mentioned errors; however, the serializer is not recursing through the tree.  Instead its assigning a null values to my "ParentID":

I am using Overwatch and some of its characters to visualize the relationships.   Ideally, the tree will be as such:
-Overwatch
-----Ana
----------Pharah
-----Soldier 76
-----Tracer

Before "ParentID = RecursiveField(allow_null=True, required=False, many=True)":
```
{
        "ClientID": 234,
        "Name": "Overwatch",
        "BusinessUnitID": 1,
        "ParentID": null,
        "InvoicePreFix": "OWH",
        "BillingTerms": 30,
        "BillingInterval": 4,
        "MaximumAllowedExposure": "5000.00",
        "InvoiceTypeID": 1
    },
    {
        "ClientID": 235,
        "Name": "Ana",
        "BusinessUnitID": 2,
        "ParentID": 234,
        "InvoicePreFix": "SLP",
        "BillingTerms": 5,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "50.00",
        "InvoiceTypeID": 3
    },
    {
        "ClientID": 236,
        "Name": "Soldier 76",
        "BusinessUnitID": 2,
        "ParentID": 234,
        "InvoicePreFix": "SIX",
        "BillingTerms": 15,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "100.00",
        "InvoiceTypeID": 3
    },
    {
        "ClientID": 237,
        "Name": "Tracer",
        "BusinessUnitID": 4,
        "ParentID": 234,
        "InvoicePreFix": "PRI",
        "BillingTerms": 15,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "30.00",
        "InvoiceTypeID": 2
    },
    {
        "ClientID": 238,
        "Name": "Pharah",
        "BusinessUnitID": 3,
        "ParentID": 235,
        "InvoicePreFix": "BAR",
        "BillingTerms": 0,
        "BillingInterval": 0,
        "MaximumAllowedExposure": "0.00",
        "InvoiceTypeID": null
    }
```

After "ParentID = RecursiveField(allow_null=True, required=False, many=True)":
```
{
        "ClientID": 234,
        "Name": "Overwatch",
        "BusinessUnitID": 1,
        "ParentID": null,
        "InvoicePreFix": "OWH",
        "BillingTerms": 30,
        "BillingInterval": 4,
        "MaximumAllowedExposure": "5000.00",
        "InvoiceTypeID": 1
    },
    {
        "ClientID": 235,
        "Name": "Ana",
        "BusinessUnitID": 2,
        "ParentID": null,
        "InvoicePreFix": "SLP",
        "BillingTerms": 5,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "50.00",
        "InvoiceTypeID": 3
    },
    {
        "ClientID": 236,
        "Name": "Soldier 76",
        "BusinessUnitID": 2,
        "ParentID": null,
        "InvoicePreFix": "SIX",
        "BillingTerms": 15,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "100.00",
        "InvoiceTypeID": 3
    },
    {
        "ClientID": 237,
        "Name": "Tracer",
        "BusinessUnitID": 4,
        "ParentID": null,
        "InvoicePreFix": "PRI",
        "BillingTerms": 15,
        "BillingInterval": 1,
        "MaximumAllowedExposure": "30.00",
        "InvoiceTypeID": 2
    },
    {
        "ClientID": 238,
        "Name": "Pharah",
        "BusinessUnitID": 3,
        "ParentID": null,
        "InvoicePreFix": "BAR",
        "BillingTerms": 0,
        "BillingInterval": 0,
        "MaximumAllowedExposure": "0.00",
        "InvoiceTypeID": null
    }
```

**Comment by heywbj** [comment]
Can you post your updated model?

If you look in the tests.py file for examples, you can follow something like this.


    class RecursiveModel(models.Model):
        name = models.CharField(max_length=255)
        parent = models.ForeignKey('self', null=True, on_delete=models.CASCADE)


    class RecursiveModelSerializer(serializers.ModelSerializer):
        parent = RecursiveField(allow_null=True)
    
        class Meta:
            model = RecursiveModel
            fields = ('name', 'parent')
