### ISSUE TITLE
How to use children?

### ISSUE THREAD

**Issue by LennyLip** [heywbj/django-rest-framework-recursive#3]
Model:

```
class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name=_('Title'), db_index=True)
    parent = models.ForeignKey('self', related_name="children", null=True, blank=True)
```

Seralizer:

```
class CategorySerializer(serializers.ModelSerializer):
    children = serializers.ListField(child=RecursiveField())

    class Meta:
        model = Category
        fields = ('id', 'title', 'children')  
```

It is does not work (it should?) with TypeError: 'RelatedManager' object is not iterable .

Hm, seems it is DRF issue, because

```
children = serializers.ListField() 
```

does not work too.

only this is work, returned ids only.

```
class CategorySerializer(serializers.ModelSerializer):

    class Meta:
        model = Category
        fields = ('id', 'title', 'children')  
```

Can you held with this, or close issue...

**Comment by LennyLip** [comment]
it is work now!

```
class CategorySerializer(serializers.ModelSerializer):
   children = serializers.ListSerializer(read_only=True, child=RecursiveField())

   class Meta:
       model = Category
       fields = ('id', 'title', 'children')  
```

**Comment by LennyLip** [comment]
Also i've add  to a ListApiView:
     queryset = Category.objects.filter(parent__exact=None)  #only root categories

but now i have a problem.

as i see, django-rest-framework-recursive children is not compatible with pagination, so we must use it with small sets of data, am i right?

ps. Thanks for application!

**Comment by heywbj** [comment]
I am not sure it would make sense to paginate the 'children' of a recursively serialized model. For instance, how would you represent the children of the children (grandchildren)? I'm not sure it is desirable.

In any case, to answer your question, you can use it with a dataset of any size you desire, but if you want to display the entire serialized result on-page, you would probably want to make sure it is limited in size...

**Comment by ghost** [comment]
It seems that this problem still exists.

My model:

```
class Chapter(MPTTModel):
    parent = TreeForeignKey('self', null = True, blank = True, related_name = 'children')
    name = models.CharField(max_length = 150)
    image = ProcessedImageField(
        upload_to = 'chapters/%Y/%m/%d',
        null = True,
        blank = True,
        default = None,
        processors=[ResizeToFill(480, 320)],
        format='PNG',
        options={'quality': 60}
    )

    def __unicode__(self):
        return self.name

    @property
    def base64_image( self ):
        try:
            img = open( self.image.path, "rb")
            data = img.read()
            return "data:image/png;base64,%s" % data.encode('base64')

        except IOError:
            return self.image.url
```

Serializer:

```
class ChapterSerializer(serializers.ModelSerializer):
    parent = RecursiveField(allow_null = True)
    children = serializers.ListField(read_only = True, child=RecursiveField())
    pages = PageSerializer(source='page_set', many = True, read_only = True)
    class Meta:
        model = Chapter
        fields= ('id', 'base64_image', 'name', 'parent', 'children', 'pages')
```

view:

```
class ChapterViewSet(viewsets.ModelViewSet):
    queryset = Chapter.objects.all()
    serializer_class = ChapterSerializer
```

So I've followed the suggestion above, but I still get the error: 'RelatedManager' object is not iterable'. What should I do to serialize the MPTT tree?

I'm using django 1.8, and DRF 3.

**Comment by heywbj** [comment]
`chapter.children` is going to be a `RelatedManager` and, indeed, not iterable. To get around this you might be able to use the `source` and set it to `source=children.all`. You could also an attr accessor to get at the children. I haven't tried either of these but feel free to give them a shot.

You probably don't want to have both the parent and children represented by recursive fields, as when you serialize the children, each of them will serialize the parent, who will in turn serialize the children......
