### ISSUE TITLE
How to reach childs after filtering them out.

### ISSUE THREAD

**Issue by aliscie** [heywbj/django-rest-framework-recursive#33]
to prevent reaching the max recursion depth I filtered out the childs from the api. Now, I can't update them at all for example,  I used ```     queryset = elements.objects.filter(parent__isnull=True)
```
then when I enter child object id like this
http://127.0.0.1:8000/elements/27
I shows 
```
HTTP 404 Not Found
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Not found."
}
```

`urls.py`

```
from .views import elementsVeiwSet, stylesVeiwSet, componentsVeiwSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('elements', elementsVeiwSet, basename='elements')
urlpatterns = router.urls
```

**Comment by heywbj** [comment]
Sorry for extremely slow reply. Your max recursion depth issue might be related to #32 , but without a stack trace impossible to tell. I can't debug your full stack application for you, unfortunately -- it involves many different modules that have no relationship to this package. You will need to boil down your issue further.
