### ISSUE TITLE
GET call not returning id

### ISSUE THREAD

**Issue by ctippur** [heywbj/django-rest-framework-recursive#6]
Hello,

This plugin is extremely useful. Thanks again.

I seem to have  a small issue with it. 

Model:

class RecursiveModel(models.Model):
    stage_title = models.CharField(max_length=255, unique=True)
    parent = models.ForeignKey('self', null=True)
    created = models.DateTimeField(auto_now_add=True)

View:
class MySerializer(serializers.ModelSerializer):
    parent = RecursiveField(allow_null=True, read_only=True)
    class Meta:
        managed = True
        model = RecursiveModel
        fields = ( 'stage_title', 'parent')

In the view, I am unable to get a ID of the model object. As a result, I get all the aspects but I cannot drill down on parent id.
Appreciate any help in this regard.

**Comment by heywbj** [comment]
Does `fields = ('id', ... )` work ?

**Comment by ctippur** [comment]
Terribly sorry. My bad. Yes I added ID to serializer and it works.
- Shekar
