### ISSUE TITLE
Run raw queries

### ISSUE THREAD

**Issue by ctippur** [heywbj/django-rest-framework-recursive#7]
Hello,

I need to be able to run query on a recursive model that gives the name of the parent and child

My model

class RecursiveModel(models.Model):
   stage_title = models.CharField(max_length=255, unique=True)
    parent = models.ForeignKey('self', null=True)

I need to get the names of parent and child relationship
Equivalant query being:

select c.id, c.stage_title as child, p.stage_title as parent from recursivemodel c, recursivemodel p  where c.parent_id=p.id

How do I do that?
- Shekar

**Comment by ctippur** [comment]
When I run it, I get:

Cannot assign "'stgabc'": "RecursiveModel_Deferred_created_data_parent_id_stage_title.parent" must be a "RecursiveModel" instance.

**Comment by heywbj** [comment]
This question has nothing to do with recursive serialization.

```
instance  = RecursiveModel.objects.select_related('parent').get(id=...)
print(instance.name)
print(instance.parent.name)
```
