### ISSUE TITLE
Children List is always NULL

### ISSUE THREAD

**Issue by veris-neerajdhiman** [heywbj/django-rest-framework-recursive#8]
Hi,

I am using this package to get all children of any node.
Here is my Model and Serializer : 

```
class VenueSerializer(serializers.HyperlinkedModelSerializer):
    children = RecursiveField(source='children.all', many=True, read_only=True)

    class Meta:
        model = Venue
        fields = ( 'name', 'description','children',)

class Venue(MPTTModel):
    name = models.CharField(_('name'), max_length=100)
    description = models.TextField(_('description'), null=True, blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
        db_index=True, verbose_name=_('parent'))
```

But I am getting children list NULL 

``` js
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "name": "first Venue",
      "description": "testing purpose",
      "children": [
        {},
        {}
      ]
    }
  ]
}
```

Any idea where I am getting things wrong

**Comment by veris-neerajdhiman** [comment]
Sorry my Bad, Your RecursiveField was overwitten by mine.

**Comment by veris-neerajdhiman** [comment]
Hi again :)

One more issue arised due to this `Recursive` field.
My Model has one more field `is_deleted` so I am filtering data using this field as I did in my view below : 

```
class GroupViewSet(viewsets.ReadOnlyModelViewSet):

    queryset = Group.objects.all()
    permission_classes = (IsIdentifyUser, )
    serializer_class = VenueSerializer
    filter_backends = (ModifiedAtFilterBackend,)

    def get_queryset(self, *args, **kwargs):
        queryset = super(GroupViewSet, self).get_queryset(*args, **kwargs)
        queryset = queryset.objects.filter(level=0).exclude(is_deleted=True)
        return queryset
```

But its not filtering the children 
I have tried this to `queryset.objects.filter(is_deleted=False, level=0)` same thing anyway. But None is working.

may be its because My serializer includes `source = 'children.all'`. But How will I exclude some children then, If I'll remove this `source = 'children.all'` then it'll raise an error `Related manager not itratble`

**Comment by veris-neerajdhiman** [comment]
@heywbj  Any Solution

**Comment by heywbj** [comment]
If you are trying to avoid serializing deleted children, you could make a read-only attribute on venue, e.g. `venue.active_children` and use source='active_children`. 

This doesn't really have anything to do with the `RecursiveField` itself, so I'm going to close this ticket for now.

**Comment by veris-neerajdhiman** [comment]
@heywbj  Can you explain it a little bit or by demo in my code itself
