### ISSUE TITLE
required is not propagated on children

### ISSUE THREAD

**Issue by j-san** [heywbj/django-rest-framework-recursive#9]
example:

```
class StuffSerializer(serializers.ModelSerializer):
  children = RecursiveField(many=True, required=False, allow_null=True)
```

works fine if I send:

```
{...}
```

but if I send children, children of children are required:

```
{
  "children": [
    {...},
    {...}
  ]
}

// response:
{
  "children":[
    {"children":["This field may not be null."]},
    {"children":["This field may not be null."]}
  ]
}
```

And finally works if I send empty children of children:

```
{
  "children": [
    {..., "children": []},
    {..., "children": []}
  ]
}
```

**Comment by heywbj** [comment]
https://github.com/heywbj/django-rest-framework-recursive/blob/master/tests/test_recursive.py#L102
https://github.com/heywbj/django-rest-framework-recursive/blob/master/tests/test_recursive.py#L16
https://travis-ci.org/heywbj/django-rest-framework-recursive/jobs/97511834

Seems to work fine. What version of django/django-rest-framework are you using?

closing for now. Reopen the ticket if you can't figure it out.

**Comment by j-san** [comment]
Django == 1.8
drf == 3.1.1
Upgraded and tested to drf 3.3 and it works like a charm ! Thank you for your help :)
